name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'
    paths-ignore: [.github/**]
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo: "Branch: ${{ github.ref }}"
          echo: "Repo: ${{ github.GITHUB_REPOSITORY }}"
      - name: List Files
        run: |
          tree
