name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: World
        description: Who to greet
    outputs:
      current-time:
        value: ${{ jobs.reusable-job.outputs.time }}
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    name: reusable-job
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }}"
      - id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
